# Generated by Django 3.2.4 on 2021-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('lore', models.CharField(max_length=2000)),
                ('abilityNameQ', models.CharField(max_length=100)),
                ('abilityDescriptionQ', models.CharField(max_length=100)),
                ('abilityNameW', models.CharField(max_length=100)),
                ('abilityDescriptionW', models.CharField(max_length=100)),
                ('abilityNameE', models.CharField(max_length=100)),
                ('abilityDescriptionE', models.CharField(max_length=100)),
                ('abilityNameR', models.CharField(max_length=100)),
                ('abilityDescriptionR', models.CharField(max_length=100)),
            ],
        ),
    ]
