# Generated by Django 3.2.4 on 2021-07-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='comments',
            field=models.ManyToManyField(to='main_app.Comment'),
        ),
    ]
