# Generated by Django 3.2.4 on 2021-07-06 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_champion_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='champion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.champion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.champion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
