# Generated by Django 3.2.4 on 2021-07-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210706_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='champion',
            field=models.CharField(max_length=100),
        ),
    ]
