# Generated by Django 3.2.4 on 2021-07-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='champion',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
